content: 
  - name: Projects
    path: files
    type: collection
    fields: 
      - {name: title, type: string}
      - {name: Description, type: string}
      - {name: Roles, type: string}
      - {name: Client, type: string}
      - {name: Project_Details, type: rich-text}
      - {name: Project_link, type: rich-text}
      - {name: Images, type: image}


media: input
media:
- name: cover
  label: Cover
  type: image
  list: true
  options:
    path: HamzaPatel/images
    extensions: [ jpg, jpeg, png ]